#!/bin/sh
MAKE="100"

## Set compiler location
echo Setting compiler location...
export ARCH=arm
export CROSS_COMPILE=/home/sultan/Downloads/arm-cortex_a8-linux-gnueabi-linaro_4.7.4-2013.09/bin/arm-cortex_a8-linux-gnueabi-

## Build Sultan kernel
make -j$MAKE ARCH=arm


