#!/bin/sh
MAKE="100"

## Set compiler location
echo Setting compiler location...
export ARCH=arm
export CROSS_COMPILE=$HOME/Downloads/arm-unknown-linux-gnueabi-linaro_4.7.4-2013.11/bin/arm-gnueabi-

## Build Sultan kernel
rm -f $HOME/sultan-kernel-grouper-metallice/arch/arm/boot/zImage
make -j$MAKE ARCH=arm
sleep 1
echo Zipping and copying zImage
sleep 1
rm -f $HOME/sultan-kernel-grouper-metallice/arch/arm/boot/zImage.zip
cd $HOME/sultan-kernel-grouper-metallice/arch/arm/boot
zip zImage.zip zImage
if [ -e $HOME/Documents/Nexus_7 ]; then
rm -f $HOME/Documents/Nexus_7/zImage.zip
cp $HOME/sultan-kernel-grouper-metallice/arch/arm/boot/zImage.zip $HOME/Documents/Nexus_7
rm -f $HOME/sultan-kernel-grouper-metallice/arch/arm/boot/zImage.zip
else
mkdir $HOME/Documents/Nexus_7
rm -f $HOME/Documents/Nexus_7/zImage.zip
cp $HOME/sultan-kernel-grouper-metallice/arch/arm/boot/zImage.zip $HOME/Documents/Nexus_7
rm -f $HOME/sultan-kernel-grouper-metallice/arch/arm/boot/zImage.zip
fi
cd $HOME/sultan-kernel-grouper-metallice
